version: '3.1'

services:
  comma-fixer:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: comma-fixer
    command: uvicorn --host 0.0.0.0 --port 8000 "app:app" --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/comma-fixer
