version: '3.1'

services:
#  nginx:
#    image: nginx:latest
#    container_name: nginx
#    volumes:
#      - ./:/comma-fixer
#      - ./nginx.conf:/etc/nginx/conf.d/default.conf
#    ports:
#      - 8001:80
#    networks:
#      - my-network
#    depends_on:
#      - flask
  comma-fixer:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: comma-fixer
    command: uvicorn --host 0.0.0.0 --port 8000 "app:app"
    volumes:
      - ./:/comma-fixer
#    networks:
#      my-network:
#        aliases:
#          - comma-fixer
#
#networks:
#  my-network: